
# 12 MHz clock
set_property PACKAGE_PIN F5      [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]


# seven-segment: digit 0
set_property PACKAGE_PIN C1  [get_ports dig0[0]]
set_property PACKAGE_PIN C2  [get_ports dig0[1]]
set_property PACKAGE_PIN C3  [get_ports dig0[2]]
set_property PACKAGE_PIN F2  [get_ports dig0[3]]
set_property PACKAGE_PIN E1  [get_ports dig0[4]]
set_property PACKAGE_PIN D3  [get_ports dig0[5]]
set_property PACKAGE_PIN E2  [get_ports dig0[6]]
set_property PACKAGE_PIN B1  [get_ports dig0[7]]
set_property IOSTANDARD LVCMOS33 [get_ports dig0[0]]
set_property IOSTANDARD LVCMOS33 [get_ports dig0[1]]
set_property IOSTANDARD LVCMOS33 [get_ports dig0[2]]
set_property IOSTANDARD LVCMOS33 [get_ports dig0[3]]
set_property IOSTANDARD LVCMOS33 [get_ports dig0[4]]
set_property IOSTANDARD LVCMOS33 [get_ports dig0[5]]
set_property IOSTANDARD LVCMOS33 [get_ports dig0[6]]
set_property IOSTANDARD LVCMOS33 [get_ports dig0[7]]

# seven-segment: digit 1
set_property PACKAGE_PIN B6  [get_ports dig1[0]]
set_property PACKAGE_PIN C7  [get_ports dig1[1]]
set_property PACKAGE_PIN A8  [get_ports dig1[2]]
set_property PACKAGE_PIN A3  [get_ports dig1[3]]
set_property PACKAGE_PIN A4  [get_ports dig1[4]]
set_property PACKAGE_PIN A5  [get_ports dig1[5]]
set_property PACKAGE_PIN B5  [get_ports dig1[6]]
set_property PACKAGE_PIN B7  [get_ports dig1[7]]
set_property IOSTANDARD LVCMOS33 [get_ports dig1[0]]
set_property IOSTANDARD LVCMOS33 [get_ports dig1[1]]
set_property IOSTANDARD LVCMOS33 [get_ports dig1[2]]
set_property IOSTANDARD LVCMOS33 [get_ports dig1[3]]
set_property IOSTANDARD LVCMOS33 [get_ports dig1[4]]
set_property IOSTANDARD LVCMOS33 [get_ports dig1[5]]
set_property IOSTANDARD LVCMOS33 [get_ports dig1[6]]
set_property IOSTANDARD LVCMOS33 [get_ports dig1[7]]

# seven-segment: digit 2
set_property PACKAGE_PIN B11 [get_ports dig2[0]]
set_property PACKAGE_PIN A12 [get_ports dig2[1]]
set_property PACKAGE_PIN A13 [get_ports dig2[2]]
set_property PACKAGE_PIN C8  [get_ports dig2[3]]
set_property PACKAGE_PIN A9  [get_ports dig2[4]]
set_property PACKAGE_PIN B10 [get_ports dig2[5]]
set_property PACKAGE_PIN A10 [get_ports dig2[6]]
set_property PACKAGE_PIN B12 [get_ports dig2[7]]
set_property IOSTANDARD LVCMOS33 [get_ports dig2[0]]
set_property IOSTANDARD LVCMOS33 [get_ports dig2[1]]
set_property IOSTANDARD LVCMOS33 [get_ports dig2[2]]
set_property IOSTANDARD LVCMOS33 [get_ports dig2[3]]
set_property IOSTANDARD LVCMOS33 [get_ports dig2[4]]
set_property IOSTANDARD LVCMOS33 [get_ports dig2[5]]
set_property IOSTANDARD LVCMOS33 [get_ports dig2[6]]
set_property IOSTANDARD LVCMOS33 [get_ports dig2[7]]
